
CREATE TABLE ACTIVITY

ID INTEGER,
NAME VARCHAR2(200)
STATE INTEGER,
ESTIMATED_DATE DATE, 
EMPLOYEE INTEGER,
CONSTRAINT ACTIVITY_pk PRIMARY KEY(CODIGO)
CONSTRAINT ACTIVITY_EMPLOYEE_FK FOREIGN KEY (EMPLOYEE) REFERENCES EMPLOYEE (ID);
CONSTRAINT ACTIVITY_STATE_FK FOREIGN KEY (STATE) REFERENCES STATE (ID);

--------------------------------------
CREATE TABLE EMPLOYEE

ID INTEGER,
NAME VARCHAR2(200),
CONSTRAINT FACTURA_pk PRIMARY KEY(ID)
CONSTRAINT FACTURA_CLIENTE_FK FOREIGN KEY (CLI_DOCUMENTO,CLI_TIPO_DOCUMENTO) REFERENCES CLIENTES (DOCUMENTO,TIPO_DOCUMENTO)
CONSTRAINT FACTURA_MANTO_FK FOREIGN KEY (COD_MANTENIMIENTO) REFERENCES MANTENIMIENTO (CODIGO);

-------------------------------------------

CREATE TABLE STATE

ID INTEGER,
NAME VARCHAR2(200)
CONSTRAINT FACTURA_pk PRIMARY KEY(ID) 












